### ISSUE TITLE
Provide more detailed documentation

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphql-link#47]
1) CLI commands reference
2) Clone getting started from readme
3) Add features section (from readme)

**Comment by ankithans** [comment]
I'm on it!

**Comment by wtrocki** [comment]
@ankithans do you know golang?

**Comment by ankithans** [comment]
@wtrocki Actually no, just know the basics. But trying to learn it!

**Comment by wtrocki** [comment]
awesome work done by ankit hans
